# Generated by Django 5.1.6 on 2025-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_logo', models.ImageField(blank=True, help_text='Logo principal del sistema', null=True, upload_to='logos/')),
                ('secondary_logo', models.ImageField(blank=True, help_text='Logo secundario del sistema', null=True, upload_to='logos/')),
            ],
        ),
    ]
