# Generated by Django 5.1.6 on 2025-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_logo',
            field=models.FileField(blank=True, help_text='Logo principal del sistema', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='secondary_logo',
            field=models.FileField(blank=True, help_text='Logo secundario del sistema', null=True, upload_to='logos/'),
        ),
    ]
