# Generated by Django 5.1.6 on 2025-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='cod',
            field=models.CharField(max_length=100),
        ),
    ]
