# Generated by Django 5.1.4 on 2025-02-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('asset_type', models.CharField(choices=[('tool', 'Herramienta'), ('vehicle', 'Vehículo'), ('equipment', 'Equipo de calibración'), ('facility', 'Infraestructura'), ('software', 'Software'), ('supply', 'Insumo/Repuesto'), ('personnel', 'Personal'), ('other', 'Otro')], default='other', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('maintenance', 'En mantenimiento'), ('damaged', 'Dañado'), ('retired', 'Retirado')], default='available', max_length=20)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_fields', models.JSONField(default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='supply.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='supply.asset')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(blank=True, max_length=100, null=True)),
                ('new_location', models.CharField(max_length=100)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='supply.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
