# Generated by Django 5.1.6 on 2025-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_assetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
