# Generated by Django 5.1.6 on 2025-03-05 21:10

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_area_cod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('paternal_surname', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('controlled', models.BooleanField(default=False, help_text='¿Cuenta con registro de control sanitario?', verbose_name='Controlado')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Soltero'), ('married', 'Casado'), ('divorced', 'Divorciado'), ('widowed', 'Viudo')], max_length=20, null=True, verbose_name='Estado civil')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de emergencia')),
                ('position', models.CharField(blank=True, max_length=70, null=True, verbose_name='Cargo')),
                ('headquarters', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sede')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contratación')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('contract_type', models.CharField(blank=True, choices=[('permanent', 'Permanente'), ('temporary', 'Temporal')], max_length=50, null=True, verbose_name='Tipo de contrato')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area', verbose_name='Área')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Departamento')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rrhh.employee', verbose_name='Padre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
