# Generated by Django 5.1.6 on 2025-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='headquarters',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
