# Generated by Django 5.1.6 on 2025-03-04 21:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_employee_headquarters_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='employee',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rrhh.employee', verbose_name='Padre'),
        ),
    ]
