# Generated by Django 5.1.6 on 2025-03-05 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_area_cod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_at', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('created', 'Creada'), ('approved', 'Aprobada'), ('approved_by_accounting', 'V°B° de Contabilidad'), ('rendered', 'Rendida'), ('rejected', 'Rechazada')], default='draft', max_length=30)),
                ('oti', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_reports', to='core.area')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_reports', to='core.department')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.period')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitationAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, help_text='Número del comprobante', max_length=50, null=True)),
                ('voucher_file', models.FileField(blank=True, help_text='Archivo del comprobante (PDF o imagen)', null=True, upload_to='vouchers/')),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
            },
        ),
        migrations.CreateModel(
            name='SolicitationApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('employee', 'Empleado'), ('manager', 'Gerente'), ('rrhh', 'Recursos Humanos'), ('finance', 'Finanzas')], max_length=30)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='solicitations.solicitation')),
            ],
            options={
                'verbose_name': 'Aprobación de solicitud',
                'verbose_name_plural': 'Aprobaciones de solicitud',
            },
        ),
    ]
