# Generated by Django 5.1.6 on 2025-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='solicitation_type',
            field=models.CharField(choices=[('exit_ticket', 'Papeleta de salida'), ('expenses', 'Entradas por rendir'), ('petty_cash', 'Caja chica'), ('mobility_sheet', 'Planilla de movilidad'), ('perdiem_request', 'Solicitud de viáticos')], default='perdiem_request', max_length=50),
        ),
    ]
