# Generated by Django 5.1.6 on 2025-03-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('solicitations', '0003_alter_solicitation_solicitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitations', to='planning.workorder'),
        ),
    ]
