# Generated by Django 5.1.6 on 2025-03-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_solicitation_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales para la papeleta de salida.', null=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_ticket_detail', to='solicitations.solicitation')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales para entregas por rendir.', null=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_detail', to='solicitations.solicitation')),
            ],
        ),
        migrations.CreateModel(
            name='MobilitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales para planilla de movilidad.', null=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobility_sheet_detail', to='solicitations.solicitation')),
            ],
        ),
        migrations.CreateModel(
            name='PerdiemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales para solicitud de viáticos.', null=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perdiem_request_detail', to='solicitations.solicitation')),
            ],
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales para caja chica.', null=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_detail', to='solicitations.solicitation')),
            ],
        ),
    ]
