# Generated by Django 5.1.6 on 2025-03-11 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_proforma_client'),
        ('solicitations', '0005_exitticket_expenses_mobilitysheet_perdiemrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitation',
            name='oti',
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.client'),
        ),
    ]
