# Generated by Django 5.1.6 on 2025-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0006_remove_solicitation_oti_alter_solicitation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='solicitation_type',
            field=models.CharField(blank=True, choices=[('exit_ticket', 'Papeleta de salida'), ('expenses', 'Entregas por rendir'), ('petty_cash', 'Caja chica'), ('mobility_sheet', 'Planilla de movilidad'), ('perdiem_request', 'Solicitud de viáticos')], max_length=50, null=True),
        ),
    ]
