# Generated by Django 5.1.6 on 2025-03-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0007_alter_solicitation_solicitation_type'),
        ('supply', '0003_asset_quantity_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('alimentacion', 'Alimentación'), ('movilidad_local', 'Movilidad local'), ('pasaje_terrestre', 'Pasaje terrestre'), ('peaje', 'Peaje'), ('pasaje_aereo', 'Pasaje aéreo'), ('alojamiento', 'Alojamiento'), ('combustible', 'Combustible'), ('reparaciones', 'Reparaciones'), ('otros', 'Otros')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_per_day', models.PositiveIntegerField(default=1)),
                ('type_item', models.CharField(choices=[('diario', 'Gasto diario'), ('unico', 'Gasto único')], default='unico', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Viatico',
                'verbose_name_plural': 'Viaticos',
            },
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='persons',
            field=models.ManyToManyField(related_name='viajantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='perdiemrequest',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='supply.asset'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='solicitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='solicitations.solicitation'),
        ),
        migrations.AlterField(
            model_name='mobilitysheet',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilitysheet',
            name='solicitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobility_sheet', to='solicitations.solicitation'),
        ),
        migrations.AlterField(
            model_name='perdiemrequest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perdiemrequest',
            name='solicitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perdiem', to='solicitations.solicitation'),
        ),
        migrations.CreateModel(
            name='PerDiemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('currency', models.CharField(choices=[('DOLARES', 'Dolares'), ('SOLES', 'Soles')], default='SOLES', max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('state', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdiem_item', to='solicitations.perdiem')),
                ('request_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdiem_request_item', to='solicitations.perdiemrequest')),
            ],
            options={
                'verbose_name': 'Item de solicitude',
                'verbose_name_plural': 'Items de solicitudes',
            },
        ),
    ]
