# Generated by Django 5.1.6 on 2025-03-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0008_perdiem_perdiemrequest_days_perdiemrequest_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilitysheet',
            name='details',
        ),
        migrations.AddField(
            model_name='mobilitysheet',
            name='correlative',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mobilitysheet',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilitysheet',
            name='total_items',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MobilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('transport', models.CharField(blank=True, choices=[('TAXI', 'Taxi'), ('BUS', 'Transporte colectivo')], max_length=100, null=True)),
                ('daily_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approver_signature', models.BooleanField(default=False)),
                ('mobility_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='solicitations.mobilitysheet')),
            ],
        ),
    ]
