# Generated by Django 5.1.6 on 2025-03-15 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_costcenter'),
        ('solicitations', '0009_remove_mobilitysheet_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_items', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('correlative', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='solicitations.solicitation')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('ruc_or_dni', models.CharField(max_length=20)),
                ('provider_name', models.CharField(default='No encontrado', max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('doc_type', models.CharField(choices=[('F', 'Factura'), ('RH', 'Recibo por Honorario'), ('BOL', 'Boleta')], max_length=10)),
                ('doc', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='expenditure_details/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_details', to='core.costcenter')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitations.expense')),
            ],
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
