# Generated by Django 5.1.6 on 2025-03-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0005_alter_proforma_client'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('assets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assets', to='supply.asset')),
                ('equipments', models.ManyToManyField(blank=True, related_name='work_orders', to='commercial.equipment')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='commercial.proforma')),
            ],
        ),
    ]
