# Generated by Django 5.1.6 on 2025-03-06 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('address', models.TextField(default='Direccion')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('economic_activity', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('is_retention_agent', models.BooleanField(default=False)),
                ('workers_number', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('accounting_type', models.CharField(blank=True, max_length=50, null=True)),
                ('foreign_trade', models.CharField(blank=True, max_length=50, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('contado', 'Al contado'), ('credito', 'Credito')], default='Contado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('sales_advisor', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'COMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='commercial.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('billing', 'Responsable de Facturación'), ('payment', 'Responsable de Pago'), ('compliance', 'Responsable de Conformidad'), ('certificate', 'Contacto para Certificado Digital'), ('user', 'Usuario del Servicio')], max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='commercial.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commercial.client')),
            ],
        ),
    ]
