# Generated by Django 5.1.6 on 2025-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_branch_district_branch_province_branch_ubigeo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del instrumento de medición.', max_length=255, verbose_name='Instrumento de medición o artefacto')),
                ('discipline', models.CharField(help_text='Seleccione la disciplina o magnitud a la que pertenece el instrumento.', max_length=255, verbose_name='Disciplina / Magnitud')),
                ('subdiscipline', models.CharField(blank=True, help_text='Indique una subdisciplina específica, si aplica.', max_length=255, null=True, verbose_name='Subdisciplina')),
                ('procedure_code', models.CharField(help_text='Código del procedimiento de calibración o verificación.', max_length=10, verbose_name='Código del Procedimiento')),
                ('procedure', models.TextField(help_text='Descripción del procedimiento utilizado.', verbose_name='Procedimiento')),
                ('commercial_area_notes', models.TextField(blank=True, help_text='Cualquier observación relevante para el área comercial.', null=True, verbose_name='Notas para el Área Comercial')),
                ('measurement_range_from', models.CharField(help_text='Valor mínimo del intervalo de medición.', max_length=50, verbose_name='Intervalo de Medida Desde')),
                ('measurement_range_to', models.CharField(help_text='Valor máximo del intervalo de medición.', max_length=50, verbose_name='Intervalo de Medida Hasta')),
                ('indicator_resolution', models.CharField(help_text='Precisión o resolución del indicador del instrumento.', max_length=50, verbose_name='Resolución del Indicador')),
                ('brand', models.CharField(blank=True, help_text='Marca del instrumento.', max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, help_text='Modelo del instrumento.', max_length=100, null=True, verbose_name='Modelo')),
                ('expanded_uncertainty', models.CharField(blank=True, help_text='Nivel de confianza en las mediciones del instrumento.', max_length=100, null=True, verbose_name='Incertidumbre Expandida')),
                ('accredited', models.BooleanField(default=False, help_text='Indique si el instrumento está acreditado.', verbose_name='Acreditado')),
                ('accreditation_condition', models.CharField(blank=True, help_text='Detalles de la acreditación del instrumento.', max_length=100, null=True, verbose_name='Condición de Acreditación')),
                ('employed_standards', models.TextField(blank=True, help_text='Patrones de referencia utilizados.', null=True, verbose_name='Patrones Empleados')),
                ('man_hours', models.DecimalField(decimal_places=2, help_text='Horas hombre requeridas para el mantenimiento o calibración.', max_digits=10, verbose_name='Horas Hombre')),
                ('necessary_workers', models.IntegerField(default=1)),
                ('calibration_cost', models.DecimalField(decimal_places=2, help_text='Costo asociado a la calibración del instrumento.', max_digits=10, verbose_name='Costo de Calibración')),
                ('verification_cost', models.DecimalField(decimal_places=2, help_text='Costo asociado a la verificación del instrumento.', max_digits=10, verbose_name='Costo de Verificación')),
                ('preventive_maintenance_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del mantenimiento preventivo.', max_digits=10, null=True, verbose_name='Costo de Mantenimiento Preventivo')),
                ('transport_cost', models.DecimalField(decimal_places=2, help_text='Costo del transport del instrumento por km.', max_digits=10, verbose_name='Costo de transporte')),
                ('for_sale', models.BooleanField(default=False, help_text='Indique si este instrumento está disponible para la venta.', verbose_name='En Venta')),
                ('technical_notes', models.TextField(blank=True, help_text='Notas técnicas relevantes sobre el instrumento.', null=True, verbose_name='Notas Técnicas')),
                ('cost_center', models.CharField(help_text='Código del centro de costos relacionado con este instrumento.', max_length=50, verbose_name='Centro de Costos')),
                ('in_arequipa', models.BooleanField(default=False, help_text='Indique si el instrumento está ubicado en Arequipa.', verbose_name='En Arequipa')),
                ('in_lima', models.BooleanField(default=False, help_text='Indique si el instrumento está ubicado en Lima.', verbose_name='En Lima')),
                ('considerations', models.CharField(blank=True, help_text='Condiciones para el servicio del instrumento.', max_length=255, null=True, verbose_name='Consideraciones')),
            ],
        ),
    ]
