# Generated by Django 5.1.6 on 2025-03-07 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_instrument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventivo', 'PREVENTIVO'), ('calibracion', 'CALIBRACIÓN'), ('verificacion', 'VERIFICACIÓN')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('proforma_date', models.DateField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('lo_justo_arequipa', 'LO JUSTO AREQUIPA'), ('lo_justo_lima', 'LO JUSTO LIMA'), ('in_situ', 'IN SITU')], default='lo_justo', max_length=50)),
                ('offer_validity', models.IntegerField(default=15)),
                ('service_address', models.CharField(max_length=255)),
                ('certificate_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('completed', 'Completada'), ('sent', 'Enviada'), ('rejected', 'Rechazada'), ('approved', 'Aprobada'), ('accepted', 'Aceptada')], default='draft', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='commercial.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.client')),
                ('contacts', models.ManyToManyField(blank=True, null=True, to='commercial.contact')),
                ('sales_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_days', models.IntegerField(default=0)),
                ('total_workers', models.IntegerField(default=0)),
                ('total_km', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proforma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='commercial.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('magnitude', models.CharField(blank=True, max_length=100, null=True)),
                ('service_place', models.CharField(blank=True, choices=[('lo_justo', 'LO JUSTO'), ('in_situ', 'IN SITU')], default='lo_justo', max_length=50, null=True)),
                ('calibration_place', models.TextField(blank=True, null=True)),
                ('indirect_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quoted_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.instrument')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='commercial.proforma')),
                ('service', models.ManyToManyField(blank=True, null=True, to='commercial.service')),
            ],
        ),
    ]
