# Generated by Django 5.1.6 on 2025-03-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_service_proforma_proformaparameters_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.client'),
        ),
    ]
