# Generated by Django 5.1.6 on 2025-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_alter_proforma_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='man_hours',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Horas hombre requeridas para el servicio.', max_digits=10, verbose_name='Horas Hombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='necessary_workers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Costo del transporte del instrumento por km.', max_digits=10, verbose_name='Costo de transporte'),
            preserve_default=False,
        ),
    ]
