# Generated by Django 5.1.6 on 2025-03-13 17:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_equipment_man_hours_equipment_necessary_workers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformaparameters',
            old_name='subtotal',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='proformaparameters',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='proformaparameters',
            name='igv_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proformaparameters',
            name='total_additionals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proformaparameters',
            name='total_equipments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
